apiVersion: v1
kind: Service
metadata:
  name: apigee-envoy-proxy-service
spec:
  selector:
    app : apigee-envoy-proxy 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
